//
//  MovieRouter.swift
//  DemoVIPER
//
//  Created by Mayur Kamthe on 03/05/20.
//  Copyright (c) 2020 Mayur Kamthe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//protocol RouterProtocol {
//    func getFirstScreen() -> MovieViewController
//}
//

class MovieRouter {
    
    //var viewObj : MovieViewController?

     class func getFirstScreen() -> MovieViewController {
        
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier:"MovieViewController") as! MovieViewController
        
        let interacter  = MovieInteractor()
        let presenter  = MoviePresenter()
        
        view.interacterViewObj = interacter
        interacter.presenterProtocol = presenter
        presenter.viewObject = view
                
        return view
    }
}

