//
//  MovieModels.swift
//  DemoVIPER
//
//  Created by Mayur Kamthe on 03/05/20.
//  Copyright (c) 2020 Mayur Kamthe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Movie: Decodable {
    var artistId: Int?
    var collectionId: Int?
    var artistName: String?
    var trackName: String?
    var collectionName: String?
    
    
    init(artistName : String){
        self.artistName = artistName
    }
    
    init(artistId: Int,collectionId: Int, artistName:String, trackName: String,collectionName: String){
        self.artistId = artistId
        self.collectionId = collectionId
        self.artistName = artistName
        self.trackName = trackName
        self.collectionName = collectionName
    }
}

class ResultsModel: Decodable {
    
    var results = [Movie]()
    init(results: [Movie]) {
        self.results = results
    }
}

