//
//  MoviePresenter.swift
//  DemoVIPER
//
//  Created by Mayur Kamthe on 03/05/20.
//  Copyright (c) 2020 Mayur Kamthe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PresenterProtocol {
    func getDataFromInteracter(movieList: [Movie])
}
class MoviePresenter : PresenterProtocol{
    
    
    var presenter : PresenterProtocol?
    var interacter : MovieInteractor?
    var viewObject : dispalyDataOnView?
    
    
    func getDataFromInteracter(movieList: [Movie]) {
        viewObject?.displayData(movieList: movieList)
    }
    
    func fetchDataFromInteracter(){
        interacter?.getMovieDataIntrator()
    }
}
