//
//  MovieInteractor.swift
//  DemoVIPER
//
//  Created by Mayur Kamthe on 03/05/20.
//  Copyright (c) 2020 Mayur Kamthe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol getDataProtocol{
    func getMovieDataIntrator()
}

class MovieInteractor : getDataProtocol{
    
    var interactorProtocol : getDataProtocol?
    var presenterProtocol : PresenterProtocol?
    
    func getMovieDataIntrator() {
        let urlString = "https://itunes.apple.com/search?media=music&term=bollywood"
        let url = URL(string: urlString)
        //get Data
        URLSession.shared.dataTask(with: url!) { (data, response, error) in
            if error != nil {
                print("Loading data error")
            }else {
                guard let dataResponse = data else { return }
            do{
                var arrMovieData = [Movie]()
                let results = try JSONDecoder().decode(ResultsModel.self, from: dataResponse)
                //print(results)
                for movie in results.results{
                //print(movie.artistName!,":", movie.trackName!)
                arrMovieData.append(Movie(artistId: movie.artistId!, collectionId: movie.collectionId!, artistName: movie.artistName!, trackName: movie.trackName!, collectionName: movie.collectionName!))
                }
                //data pass to presenter
                self.presenterProtocol?.getDataFromInteracter(movieList: arrMovieData)
            }catch{
                    print("json error")
                }
            }
        }.resume()
    }
}
